/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Grafico;

/**
 *
 * @author Willian
 */
public class InterfaceGrafico extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGrafico
     */
    public InterfaceGrafico() {
        initComponents();
    }

    private void Limpar() {
        TextoExibicao.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        TextoExibicaoScroll = new javax.swing.JScrollPane();
        TextoExibicao = new javax.swing.JTextArea();
        BarraMenu = new javax.swing.JMenuBar();
        ImovelMenu = new javax.swing.JMenu();
        ListarMenu = new javax.swing.JMenu();
        Todos = new javax.swing.JMenu();
        CategoriaApartamentoResidencial = new javax.swing.JMenuItem();
        CategoriaCasaResidencial = new javax.swing.JMenuItem();
        CategoriaComercial = new javax.swing.JMenuItem();
        Locacao = new javax.swing.JMenu();
        ListaDisponivel = new javax.swing.JMenuItem();
        ListaIndisponivel = new javax.swing.JMenuItem();
        DisponivelVenda = new javax.swing.JMenuItem();
        IndisponivelVenda = new javax.swing.JMenuItem();
        UsuarioMenu = new javax.swing.JMenu();
        CorretoresCadastrados = new javax.swing.JMenuItem();
        PagamentoMenu = new javax.swing.JMenu();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho 01");

        TextoExibicao.setEditable(false);
        TextoExibicao.setColumns(20);
        TextoExibicao.setRows(5);
        TextoExibicaoScroll.setViewportView(TextoExibicao);

        ImovelMenu.setText("Imovel");

        ListarMenu.setText("Listar");

        Todos.setText("Todos");

        CategoriaApartamentoResidencial.setText("Categoria Apartamento Residencial");
        CategoriaApartamentoResidencial.setToolTipText("");
        CategoriaApartamentoResidencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaApartamentoResidencialActionPerformed(evt);
            }
        });
        Todos.add(CategoriaApartamentoResidencial);

        CategoriaCasaResidencial.setText("Categoria Casa Residencial");
        Todos.add(CategoriaCasaResidencial);

        CategoriaComercial.setText("Categoria Comercial");
        CategoriaComercial.setToolTipText("");
        Todos.add(CategoriaComercial);

        ListarMenu.add(Todos);

        Locacao.setText("Locação");

        ListaDisponivel.setText("Disponível");
        Locacao.add(ListaDisponivel);

        ListaIndisponivel.setText("Indisponível");
        Locacao.add(ListaIndisponivel);

        ListarMenu.add(Locacao);

        DisponivelVenda.setText("Disponível para venda");
        ListarMenu.add(DisponivelVenda);

        IndisponivelVenda.setText("Indisponível para venda e ou locação");
        ListarMenu.add(IndisponivelVenda);

        ImovelMenu.add(ListarMenu);

        BarraMenu.add(ImovelMenu);

        UsuarioMenu.setText("Usuario");

        CorretoresCadastrados.setText("Corretores cadastrados");
        CorretoresCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorretoresCadastradosActionPerformed(evt);
            }
        });
        UsuarioMenu.add(CorretoresCadastrados);

        BarraMenu.add(UsuarioMenu);

        PagamentoMenu.setText("Pagamento");
        BarraMenu.add(PagamentoMenu);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextoExibicaoScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextoExibicaoScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CorretoresCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorretoresCadastradosActionPerformed
        // TODO add your handling code here:
        Limpar();
        TextoExibicao.setText("Corretores cadastrados:");
    }//GEN-LAST:event_CorretoresCadastradosActionPerformed

    private void CategoriaApartamentoResidencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaApartamentoResidencialActionPerformed
        // TODO add your handling code here:
        Limpar();
        TextoExibicao.setText("Lista de categoria residencial:");
    }//GEN-LAST:event_CategoriaApartamentoResidencialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenuItem CategoriaApartamentoResidencial;
    private javax.swing.JMenuItem CategoriaCasaResidencial;
    private javax.swing.JMenuItem CategoriaComercial;
    private javax.swing.JMenuItem CorretoresCadastrados;
    private javax.swing.JMenuItem DisponivelVenda;
    private javax.swing.JMenu ImovelMenu;
    private javax.swing.JMenuItem IndisponivelVenda;
    private javax.swing.JMenuItem ListaDisponivel;
    private javax.swing.JMenuItem ListaIndisponivel;
    private javax.swing.JMenu ListarMenu;
    private javax.swing.JMenu Locacao;
    private javax.swing.JMenu PagamentoMenu;
    private javax.swing.JTextArea TextoExibicao;
    private javax.swing.JScrollPane TextoExibicaoScroll;
    private javax.swing.JMenu Todos;
    private javax.swing.JMenu UsuarioMenu;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
